# Generated by Django 5.0.7 on 2024-07-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('service_duration', models.CharField(max_length=100)),
                ('service_cost', models.CharField(max_length=100)),
                ('service_requirements', models.CharField(max_length=100)),
            ],
        ),
    ]
