# Generated by Django 5.0.7 on 2024-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_visa_country_remove_visa_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
